const router = require("express").Router();
const chargeRoute = require("./charge");
const projectsRoute = require("./projects");
const issuesRoute = require("./issues");
const usersRoute = require("./users");
const emailRoute = require("./email");
const userProject = require("./userproject");
const messages = require("./messages");
router.use("/charge", chargeRoute);
router.use("/projects", projectsRoute);
router.use("/issues", issuesRoute);
router.use("/users", usersRoute);
router.use("/email", emailRoute);
router.use("/user-projects", userProject);
router.use("/messages", messages);
module.exports = router;
